/**
 * bQuery.js — Full Bundle
 *
 * This is the complete bundle containing all modules for CDN usage.
 * Use this when you want all features without tree-shaking concerns.
 *
 * @module bquery/full
 *
 * @example CDN Usage (ES Modules)
 * ```html
 * <script type="module">
 *   import { $, signal, component } from 'https://unpkg.com/bquery@1/dist/full.es.mjs';
 *
 *   const count = signal(0);
 *   $('#counter').text(count.value);
 * </script>
 * ```
 *
 * @example CDN Usage (UMD/Global)
 * ```html
 * <script src="https://unpkg.com/bquery@1/dist/full.umd.js"></script>
 * <script>
 *   const { $, signal } = bQuery;
 *   const count = signal(0);
 * </script>
 * ```
 *
 * @example CDN Usage (IIFE)
 * ```html
 * <script src="https://unpkg.com/bquery@1/dist/full.iife.js"></script>
 * <script>
 *   // bQuery is available as a global variable
 *   const { $, $$ } = bQuery;
 * </script>
 * ```
 */

// ============================================================================
// Core Module: Selectors, DOM operations, events, utilities
// ============================================================================
export {
  $,
  $$,
  BQueryCollection,
  BQueryElement,
  // ── object ──
  clone,
  deepEqual,
  defaults,
  entriesTyped,
  freeze,
  get,
  has,
  hasOwn,
  invert,
  isEqual,
  isPlainObject,
  keysTyped,
  mapKeys,
  mapValues,
  merge,
  omit,
  pick,
  set,
  // ── function ──
  compose,
  curry,
  debounce,
  memoize,
  noop,
  once,
  partial,
  pipe,
  retry,
  throttle,
  // ── misc ──
  isEmpty,
  nextFrame,
  nextTick,
  parseJson,
  pollUntil,
  sleep,
  times,
  tryCatch,
  uid,
  uuid,
  // ── number ──
  average,
  clamp,
  degToRad,
  formatBytes,
  inRange,
  inverseLerp,
  lerp,
  mapRange,
  median,
  radToDeg,
  randomFloat,
  randomInt,
  round,
  roundTo,
  sum,
  toNumber,
  // ── string ──
  capitalize,
  escapeRegExp,
  lines,
  pad,
  padEnd,
  padStart,
  randomString,
  slugify,
  stripHtml,
  template,
  toCamelCase,
  toKebabCase,
  toPascalCase,
  toSnakeCase,
  toTitleCase,
  truncate,
  wordCount,
  // ── array ──
  chunk,
  chunkBy,
  compact,
  difference,
  drop,
  ensureArray,
  first,
  flatten,
  flattenDeep,
  groupBy,
  intersection,
  keyBy,
  last,
  move,
  partition,
  range,
  sample,
  shuffle,
  sortBy,
  take,
  unique,
  uniqueBy,
  zip,
  // ── type-guards ──
  isArray,
  isAsyncFunction,
  isAsyncIterable,
  isBigInt,
  isBoolean,
  isCollection,
  isDate,
  isDefined,
  isElement,
  isError,
  isFunction,
  isIterable,
  isMap,
  isNullish,
  isNumber,
  isObject,
  isPromise,
  isRegExp,
  isSet,
  isString,
  isSymbol,
  utils,
} from './core/index';
export type {
  BQueryUtils,
  DebounceOptions,
  DebouncedFn,
  FormatBytesOptions,
  MemoizedFn,
  PollUntilOptions,
  RetryOptions,
  ThrottleOptions,
  ThrottledFn,
  TryCatchResult,
} from './core/index';

// ============================================================================
// Reactive Module: Signals, computed values, effects, batching
// ============================================================================
export {
  batch,
  Computed,
  computed,
  createHttp,
  createRequestQueue,
  createRestClient,
  createUseFetch,
  deduplicateRequest,
  effect,
  effectScope,
  getCurrentScope,
  http,
  HttpError,
  isComputed,
  isSignal,
  linkedSignal,
  onScopeDispose,
  persistedSignal,
  readonly,
  Signal,
  signal,
  toValue,
  untrack,
  useAsyncData,
  useEventSource,
  useFetch,
  useInfiniteFetch,
  usePaginatedFetch,
  usePolling,
  useResource,
  useResourceList,
  useSubmit,
  useWebSocket,
  useWebSocketChannel,
  watch,
  watchDebounce,
  watchThrottle,
} from './reactive/index';
export type {
  AsyncDataState,
  AsyncDataStatus,
  AsyncWatchSource,
  ChannelMessage,
  ChannelSubscription,
  CleanupFn,
  EffectScope,
  EventSourceStatus,
  FetchInput,
  HttpClient,
  HttpProgressEvent,
  HttpRequestConfig,
  HttpResponse,
  IdExtractor,
  InfiniteState,
  Interceptor,
  InterceptorManager,
  LinkedSignal,
  MaybeSignal,
  Observer,
  PaginatedState,
  PollingState,
  ReadonlySignal,
  ReadonlySignalHandle,
  RequestQueue,
  RequestQueueOptions,
  ResourceListActions,
  RestClient,
  RetryConfig,
  UseAsyncDataOptions,
  UseEventSourceOptions,
  UseEventSourceReturn,
  UseFetchOptions,
  UseFetchRetryConfig,
  UseInfiniteFetchOptions,
  UsePaginatedFetchOptions,
  UsePollingOptions,
  UseResourceListOptions,
  UseResourceListReturn,
  UseResourceOptions,
  UseResourceReturn,
  UseSubmitOptions,
  UseSubmitReturn,
  UseWebSocketChannelOptions,
  UseWebSocketChannelReturn,
  UseWebSocketOptions,
  UseWebSocketReturn,
  WatchOptions,
  WebSocketHeartbeatConfig,
  WebSocketReconnectConfig,
  WebSocketSendData,
  WebSocketSerializer,
  WebSocketStatus,
} from './reactive/index';

// ============================================================================
// Concurrency Module: Zero-build worker task helpers
// ============================================================================
export {
  batchTasks,
  callWorkerMethod,
  createReactiveRpcPool,
  createReactiveRpcWorker,
  createReactiveTaskPool,
  createReactiveTaskWorker,
  createRpcPool,
  createRpcWorker,
  createTaskPool,
  createTaskWorker,
  every,
  filter,
  find,
  getConcurrencySupport,
  isConcurrencySupported,
  map,
  parallel,
  pipeline,
  reduce,
  runTask,
  some,
  TaskWorkerAbortError,
  TaskWorkerError,
  TaskWorkerSerializationError,
  TaskWorkerTimeoutError,
  TaskWorkerUnsupportedError,
} from './concurrency/index';
export type {
  CallWorkerMethodOptions,
  ConcurrencyPipeline,
  ConcurrencyPipelineOptions,
  ConcurrencySupport,
  CreateRpcPoolOptions,
  CreateRpcWorkerOptions,
  CreateTaskPoolOptions,
  CreateTaskWorkerOptions,
  ParallelCollectionOptions,
  ParallelMapHandler,
  ParallelMapOptions,
  ParallelOptions,
  ParallelPredicateHandler,
  ParallelReduceHandler,
  ParallelResults,
  ParallelTask,
  ReactiveRpcPool,
  ReactiveRpcWorker,
  ReactiveTaskPool,
  ReactiveTaskWorker,
  RpcPool,
  RpcWorker,
  RunTaskOptions,
  TaskPool,
  TaskRunOptions,
  TaskWorker,
  TaskWorkerErrorCode,
  TaskWorkerState,
  WorkerRpcHandler,
  WorkerRpcHandlers,
  WorkerTaskHandler,
} from './concurrency/index';

// ============================================================================
// Component Module: Web Components helper with Shadow DOM
// ============================================================================
export {
  applyAdoptedStyles,
  bindDelegatedEvents,
  bool,
  component,
  css,
  defineComponent,
  formContextKey,
  hasSlot,
  html,
  inject,
  injectionKey,
  isComponentStyles,
  keyedList,
  on,
  onChange,
  onClick,
  onInput,
  onSubmit,
  provide,
  reconcileKeyed,
  registerDefaultComponents,
  safeHtml,
  slotText,
  useAsync,
  useComputed,
  useEffect,
  useRef,
  useSignal,
  useSlot,
  whenIdle,
} from './component/index';
export type {
  AttributeChange,
  ComponentClass,
  ComponentDefinition,
  ComponentElement,
  ComponentRenderContext,
  ComponentSignalLike,
  ComponentSignals,
  ComponentStateKey,
  ComponentStateShape,
  ComponentStyles,
  DefaultComponentLibraryOptions,
  InjectionKey,
  PropDefinition,
  Ref,
  RegisteredDefaultComponents,
  ShadowMode,
  UseAsyncResult,
} from './component/index';

// ============================================================================
// Motion Module: View transitions, FLIP animations, springs, tweens, effects
// ============================================================================
export {
  animate,
  animateTo,
  animateValue,
  capturePosition,
  chain,
  countUp,
  cubicBezier,
  easeInBack,
  easeInBounce,
  easeInCirc,
  easeInCubic,
  easeInElastic,
  easeInExpo,
  easeInOutBack,
  easeInOutBounce,
  easeInOutCirc,
  easeInOutCubic,
  easeInOutElastic,
  easeInOutExpo,
  easeInOutQuad,
  easeInOutQuart,
  easeInOutQuint,
  easeInOutSine,
  easeInQuad,
  easeInQuart,
  easeInQuint,
  easeInSine,
  easeOutBack,
  easeOutBounce,
  easeOutCirc,
  easeOutCubic,
  easeOutElastic,
  easeOutExpo,
  easeOutQuad,
  easeOutQuart,
  easeOutQuint,
  easeOutSine,
  easingPresets,
  flip,
  flipElements,
  flipList,
  inView,
  keyframePresets,
  linear,
  magnetic,
  mix,
  morphElement,
  onReducedMotionChange,
  parallax,
  prefersReducedMotion,
  pulse,
  reducedMotionSignal,
  scrollAnimate,
  scrollProgress,
  sequence,
  setReducedMotion,
  shake,
  spring,
  springPresets,
  springVector,
  stagger,
  steps,
  tilt,
  timeline,
  transition,
  tween,
  typewriter,
} from './motion/index';
export type {
  AnimateOptions,
  AnimateToOptions,
  AnimateToStyles,
  CountUpOptions,
  EasingFunction,
  EffectCleanup,
  ElementBounds,
  FlipGroupOptions,
  FlipOptions,
  InViewHandle,
  InViewOptions,
  MagneticOptions,
  MorphOptions,
  ParallaxCleanup,
  ParallaxOptions,
  PulseOptions,
  ScrollAnimateCleanup,
  ScrollAnimateOptions,
  ScrollProgressCleanup,
  ScrollProgressOptions,
  SequenceOptions,
  SequenceStep,
  ShakeOptions,
  Spring,
  SpringConfig,
  SpringVector,
  SpringVectorEntry,
  StaggerFunction,
  StaggerOptions,
  StepPosition,
  TiltOptions,
  TimelineConfig,
  TimelineAt,
  TimelineControls,
  TimelineLabel,
  TimelineLabelOffset,
  TimelineRelativeOffset,
  TimelineRepeat,
  TimelineStep,
  TransitionOptions,
  TweenControls,
  TweenOptions,
  TweenValue,
  TypewriterControls,
  TypewriterOptions,
} from './motion/index';

// ============================================================================
// Security Module: Sanitization, CSP compatibility, Trusted Types
// ============================================================================
export {
  createTrustedHtml,
  escapeHtml,
  generateNonce,
  getTrustedTypesPolicy,
  hasCSPDirective,
  isTrustedTypesSupported,
  sanitize,
  sanitizeHtml,
  stripTags,
  trusted,
} from './security/index';
export type { SanitizedHtml, SanitizeOptions, TrustedHtml } from './security/index';

// ============================================================================
// Platform Module: Storage, buckets, notifications, cache
// ============================================================================
export {
  buckets,
  cache,
  defineBqueryConfig,
  definePageMeta,
  getBqueryConfig,
  notifications,
  storage,
  useAnnouncer,
  useCookie,
} from './platform/index';
export type {
  AnnounceOptions,
  AnnouncerHandle,
  BqueryAnnouncerConfig,
  BqueryComponentLibraryConfig,
  BqueryConfig,
  BqueryCookieConfig,
  BqueryFetchConfig,
  BqueryFetchParseAs,
  BqueryPageMetaConfig,
  BqueryTransitionConfig,
  Bucket,
  CacheHandle,
  IndexedDBOptions,
  NotificationOptions,
  PageLinkTag,
  PageMetaCleanup,
  PageMetaDefinition,
  PageMetaTag,
  StorageAdapter,
  UseAnnouncerOptions,
  UseCookieOptions,
} from './platform/index';

// ============================================================================
// Router Module: SPA routing, navigation guards, lazy loading
// ============================================================================
export {
  back,
  BqLinkElement,
  createRouter,
  currentRoute,
  forward,
  interceptLinks,
  isActive,
  isActiveSignal,
  isNavigating,
  link,
  navigate,
  registerBqLink,
  resolve,
  useRoute,
} from './router/index';
export type {
  NavigationGuard,
  Route,
  RouteDefinition,
  Router,
  RouterOptions,
  UseRouteReturn,
} from './router/index';

// ============================================================================
// Store Module: Signal-based state management
// ============================================================================
export {
  clearPlugins,
  createPersistedStore,
  createStore,
  defineStore,
  destroyStore,
  getStore,
  listStores,
  mapActions,
  mapGetters,
  mapState,
  registerPlugin,
  unregisterPlugin,
  watchStore,
} from './store/index';
export type {
  ActionContext,
  Actions,
  Getters,
  OnActionCallback,
  PersistedStoreOptions,
  StateFactory,
  StorageBackend,
  Store,
  StoreDefinition,
  StorePatch,
  StorePlugin,
  StoreSerializer,
  StoreSubscriber,
} from './store/index';

// ============================================================================
// View Module: Declarative DOM bindings without compiler
// ============================================================================
export { clearExpressionCache, createTemplate, mount } from './view/index';
export type { BindingContext, MountOptions, View } from './view/index';

// ============================================================================
// Forms Module: Reactive form handling and validation
// ============================================================================
export {
  all,
  arrayOf,
  between,
  bindField,
  bindForm,
  createFieldArray,
  createForm,
  custom,
  customAsync,
  dateAfter,
  dateBefore,
  email,
  field,
  fileSize,
  fileType,
  hydrateForm,
  integer,
  length,
  matchField,
  max,
  maxLength,
  min,
  minLength,
  not,
  notOneOf,
  numeric,
  oneOf,
  pattern,
  readSerializedFormState,
  required,
  requiredIf,
  requiredUnless,
  schema,
  serializeFormState,
  url,
  useField,
  useFieldArray,
  useForm,
  useFormField,
  validDate,
  withMessage,
} from './forms/index';
export type {
  AsyncValidator,
  BindFieldOptions,
  BindFormOptions,
  CrossFieldValidator,
  FieldArrayConfig,
  FieldConfig,
  FieldSchema,
  Form,
  FormChangeListener,
  FormConfig,
  FormErrors,
  FormField,
  FormFieldArray,
  FormFields,
  FormFieldValidationMode,
  FormSnapshot,
  FormValidationMode,
  FormValidationStrategy,
  SchemaEntry,
  SetFieldValueOptions,
  SubmitHandler,
  SyncValidator,
  UseFormFieldOptions,
  UseFormFieldReturn,
  UseFormFieldSetValueOptions,
  ValidationResult,
  Validator,
} from './forms/index';

// ============================================================================
// i18n Module: Internationalization, translations, formatting
// ============================================================================
export { createI18n, formatDate, formatNumber } from './i18n/index';
export type {
  DateFormatOptions,
  I18nConfig,
  I18nInstance,
  LocaleLoader,
  LocaleMessages,
  Messages,
  NumberFormatOptions,
  TranslateParams,
} from './i18n/index';

// ============================================================================
// a11y Module: Accessibility utilities
// ============================================================================
// Note: prefersReducedMotion is not re-exported here to avoid naming conflict
// with the motion module's prefersReducedMotion(). Use @bquery/bquery/a11y for
// the reactive signal version.
export {
  announceToScreenReader,
  auditA11y,
  clearAnnouncements,
  getFocusableElements,
  prefersColorScheme,
  prefersContrast,
  releaseFocus,
  rovingTabIndex,
  skipLink,
  trapFocus,
} from './a11y/index';
export type {
  AnnouncePriority,
  AuditFinding,
  AuditResult,
  AuditSeverity,
  ColorScheme,
  ContrastPreference,
  FocusTrapHandle,
  MediaPreferenceSignal,
  RovingTabIndexHandle,
  RovingTabIndexOptions,
  SkipLinkHandle,
  SkipLinkOptions,
  TrapFocusOptions,
} from './a11y/index';

// ============================================================================
// DnD Module: Drag-and-drop, drop zones, sortable lists
// ============================================================================
export { draggable, droppable, sortable } from './dnd/index';
export type {
  BoundsRect,
  DragAxis,
  DragBounds,
  DragEventData,
  DraggableHandle,
  DraggableOptions,
  DragPosition,
  DropEventData,
  DroppableHandle,
  DroppableOptions,
  SortableHandle,
  SortableOptions,
  SortEventData,
} from './dnd/index';

// ============================================================================
// Media Module: Reactive browser and device API signals
// ============================================================================
export {
  breakpoints,
  clipboard,
  clipboardText,
  mediaQuery,
  useActiveElement,
  useBattery,
  useBroadcastChannel,
  useDeviceMotion,
  useDeviceOrientation,
  useDocumentFocus,
  useElementBounding,
  useElementSize,
  useElementVisibility,
  useEventListener,
  useFocus,
  useFocusWithin,
  useGeolocation,
  useHover,
  useIdle,
  useIntersectionObserver,
  useMediaDevices,
  useMutationObserver,
  useNetworkStatus,
  useOnlineStatus,
  usePageVisibility,
  usePermission,
  usePointer,
  usePreferredColorScheme,
  usePreferredContrast,
  usePreferredLanguage,
  usePreferredLanguages,
  usePreferredReducedTransparency,
  useResizeObserver,
  useScroll,
  useShare,
  useShareSupported,
  useStorage,
  useViewport,
  useWakeLock,
  useWindowFocus,
} from './media/index';
export type {
  AbortableOptions,
  BatterySignal,
  BatteryState,
  BreakpointMap,
  BroadcastChannelHandle,
  ClipboardAPI,
  ClipboardTextOptions,
  DeviceMotionSignal,
  DeviceMotionState,
  DeviceOrientationSignal,
  DeviceOrientationState,
  ElementBoundingRect,
  ElementSize,
  GeolocationOptions,
  GeolocationSignal,
  GeolocationState,
  IntersectionObserverOptions,
  IntersectionObserverSignal,
  IntersectionObserverState,
  MediaSignalHandle,
  MutationObserverOptions,
  MutationObserverSignal,
  MutationObserverState,
  NetworkSignal,
  NetworkState,
  PointerState,
  ResizeObserverOptions,
  ResizeObserverSignal,
  ResizeObserverState,
  ScrollState,
  ShareHandle,
  StorageHandle,
  UseEventListenerOptions,
  UseIdleOptions,
  UseScrollOptions,
  UseStorageOptions,
  ViewportSignal,
  ViewportState,
  WakeLockHandle,
} from './media/index';

// ---------------------------------------------------------------------------
// Plugin module
// ---------------------------------------------------------------------------
export {
  addAction,
  addFilter,
  applyFilters,
  createInjectionKey,
  doAction,
  getCustomDirective,
  getCustomDirectives,
  getInstalledPlugins,
  getPluginInfo,
  hasProvided,
  isInstalled,
  listActions,
  listFilters,
  removeAction,
  removeFilter,
  resetDi,
  resetHooks,
  resetPlugins,
  uninstall,
  unuse,
  use,
} from './plugin/index';
export type {
  BQueryPlugin,
  CustomDirective,
  CustomDirectiveHandler,
  CustomDirectiveLifecycle,
  CustomDirectiveValue,
  PluginInfo,
  PluginInstallContext,
} from './plugin/index';

// ---------------------------------------------------------------------------
// DevTools module
// ---------------------------------------------------------------------------
export {
  clearTimeline,
  diffSignals,
  diffStores,
  enableDevtools,
  exportDevtoolsSnapshot,
  filterTimeline,
  generateSignalLabel,
  getDevtoolsState,
  getPerformanceSummary,
  getTimeline,
  importDevtoolsSnapshot,
  inspectComponents,
  inspectEffects,
  inspectSignals,
  inspectStores,
  installBrowserBridge,
  isDevtoolsEnabled,
  logComponents,
  logSignals,
  logStores,
  logTimeline,
  measureRender,
  recordEvent,
  subscribeTimeline,
  time,
  traceSignal,
  trackSignal,
  untraceSignal,
  untrackSignal,
} from './devtools/index';
export type {
  ComponentSnapshot,
  DevtoolsOptions,
  DevtoolsSnapshot,
  DevtoolsState,
  DiffChange,
  EffectSnapshot,
  ImportedDevtoolsSnapshot,
  PerformanceSummary,
  SignalSnapshot,
  StoreSnapshot,
  TimelineEntry,
  TimelineEventType,
  TimelineFilter,
} from './devtools/index';

// ---------------------------------------------------------------------------
// Testing module
// ---------------------------------------------------------------------------
export {
  fireEvent,
  flushEffects,
  mockRouter,
  mockSignal,
  renderComponent,
  waitFor,
} from './testing/index';
export type {
  FireEventOptions,
  MockRouter,
  MockRouterOptions,
  MockSignal,
  RenderComponentOptions,
  RenderResult,
  TestRoute,
  WaitForOptions,
} from './testing/index';

// ---------------------------------------------------------------------------
// SSR module
// ---------------------------------------------------------------------------
export {
  configureSSR,
  createAssetManager,
  createBunHandler,
  createDenoHandler,
  createHeadManager,
  createNodeHandler,
  createResumableState,
  createSSRContext,
  createSSRHandler,
  createSSRRouterContext,
  createWebHandler,
  defer,
  defineLoader,
  deserializeStoreState,
  detectRuntime,
  getSSRConfig,
  getSSRRuntimeFeatures,
  hydrateIsland,
  hydrateMount,
  hydrateOnIdle,
  hydrateOnInteraction,
  hydrateOnMedia,
  hydrateOnVisible,
  hydrateStore,
  hydrateStores,
  hydrateStoreSnapshot,
  HYDRATION_HASH_ATTR,
  isBrowserRuntime,
  isServerRuntime,
  readStoreSnapshot,
  renderToResponse,
  renderToStream,
  renderToStreamSuspense,
  renderToString,
  renderToStringAsync,
  resolveSSRRoute,
  resumeState,
  runRouteLoaders,
  serializeStoreSnapshot,
  serializeStoreState,
  verifyHydration,
} from './ssr/index';
export type {
  AssetManager,
  AsyncRenderOptions,
  AsyncSSRResult,
  CreateResumableStateOptions,
  CreateSSRContextOptions,
  DeserializedStoreState,
  HeadManager,
  HydrateMountOptions,
  HydrateSnapshotOptions,
  HydrateSnapshotResult,
  HydrationHandle,
  HydrationMismatch,
  HydrationOptions,
  NodeHandlerOptions,
  NodeIncomingMessage,
  NodeServerResponse,
  RenderOptions,
  RenderToResponseOptions,
  ResolvedSSRRoute,
  ResumableState,
  ResumeReader,
  SerializeOptions,
  SerializeResult,
  SerializeSnapshotOptions,
  SerializeSnapshotResult,
  SSRAsset,
  SSRContext,
  SSRDocumentImpl,
  SSRHeadState,
  SSRLink,
  SSRLoader,
  SSRMeta,
  SSRRendererBackend,
  SSRRequestHandler,
  SSRResult,
  SSRRouteLoader,
  SSRRuntime,
  SSRRuntimeFeatures,
  SSRScript,
  SSRStoreSnapshot,
  SuspenseStreamOptions,
  UseHeadOptions,
  VerifyHydrationOptions,
} from './ssr/index';

// ---------------------------------------------------------------------------
// Server module
// ---------------------------------------------------------------------------
export { createServer, isServerWebSocketSession, isWebSocketRequest } from './server/index';
export type {
  CreateServerOptions,
  ServerApp,
  ServerContext,
  ServerHandler,
  ServerHtmlResponseInit,
  ServerMiddleware,
  ServerNext,
  ServerQuery,
  ServerRenderResponseOptions,
  ServerRequestInit,
  ServerResponseInit,
  ServerResult,
  ServerRoute,
  ServerWebSocketConnection,
  ServerWebSocketData,
  ServerWebSocketHandlerSet,
  ServerWebSocketMiddleware,
  ServerWebSocketNext,
  ServerWebSocketPeer,
  ServerWebSocketRouteHandler,
  ServerWebSocketSession,
} from './server/index';
